$schema: https://azuremlschemas.azureedge.net/latest/managedOnlineEndpoint.schema.json
name: intellipipeline-endpoint
auth_mode: key
description: IntelliPipeline fraud detection online endpoint

---
$schema: https://azuremlschemas.azureedge.net/latest/managedOnlineDeployment.schema.json
name: blue
endpoint_name: intellipipeline-endpoint
model: azureml:intellipipeline-fraud-model:latest
code_configuration:
  code: .
  scoring_script: score.py
environment:
  conda_file: conda.yaml
  image: mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu20.04:latest
instance_type: Standard_DS2_v2
instance_count: 1
